### ISSUE TITLE
triton profile edit failes if EDITOR contains a space

### ISSUE THREAD

**Issue by cburroughs** [joyent/node-triton#148]
```
$ export EDITOR='nano -w'
$ triton profile edit test2
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn nano -w ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3
```

This is due to:
```js
    var kid = child_process.spawn(editor, [tmpPath], {stdio: 'inherit'});
```
where `child_proess.spawn` has a novel signature that is -- as the docs say --  "similar, but not identical, to popen(3)".

**Comment by YangYong3** [comment]
https://cr.joyent.us/#/c/1035/

**Comment by trentm** [comment]
alternative CR: https://cr.joyent.us/#/c/1586/
