### ISSUE TITLE
#108 changes broke `triton cloudapi ...`

### ISSUE THREAD

**Issue by trentm** [joyent/node-triton#154]
```
$ triton cloudapi /--ping
triton: error: Cannot read property '_request' of undefined

$ triton -v cloudapi /--ping 2>&1 | bunyan
[2016-12-14T18:48:57.319Z] TRACE: triton/16528 on danger0.local (/Users/trentm/joy/node-triton/lib/cli.js:300 in getProfile): loaded profile
    profile: {
      "url": "https://api.coal",
      "insecure": true,
      "account": "trentm",
      "keyId": "SHA256:2XCGHts...pA",
      "name": "coal"
    }
[2016-12-14T18:48:57.323Z] TRACE: triton/16528 on danger0.local (/Users/trentm/joy/node-triton/lib/cli.js:284 in getConfig): loaded config
    config: {
...
    }
[2016-12-14T18:48:57.324Z] TRACE: triton/16528 on danger0.local (/Users/trentm/joy/node-triton/lib/tritonapi.js:230 in TritonApi): cache dir (cacheDir=/Users/trentm/.triton/cache/trentm@api_coal)
[2016-12-14T18:48:57.327Z] TRACE: triton/16528 on danger0.local (/Users/trentm/joy/node-triton/lib/cli.js:340 in fini): cli fini (subcmd=cloudapi)
    TypeError: Cannot read property '_request' of undefined
        at CLI.do_cloudapi (/Users/trentm/joy/node-triton/lib/do_cloudapi.js:65:28)
        at CLI.dispatch (/Users/trentm/joy/node-triton/node_modules/cmdln/lib/cmdln.js:1257:17)
        at /Users/trentm/joy/node-triton/node_modules/cmdln/lib/cmdln.js:699:18
        at CLI.init (/Users/trentm/joy/node-triton/node_modules/cmdln/lib/cmdln.js:917:5)
        at CLI.init (/Users/trentm/joy/node-triton/lib/cli.js:334:30)
        at CLI.cmdlnMain [as main] (/Users/trentm/joy/node-triton/node_modules/cmdln/lib/cmdln.js:677:10)
        at Object.main (/Users/trentm/joy/node-triton/lib/cli.js:683:9)
        at Object.<anonymous> (/Users/trentm/joy/node-triton/bin/triton:12:23)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
triton: error: TypeError: Cannot read property '_request' of undefined
    at CLI.do_cloudapi (/Users/trentm/joy/node-triton/lib/do_cloudapi.js:65:28)
    at CLI.dispatch (/Users/trentm/joy/node-triton/node_modules/cmdln/lib/cmdln.js:1257:17)
    at /Users/trentm/joy/node-triton/node_modules/cmdln/lib/cmdln.js:699:18
    at CLI.init (/Users/trentm/joy/node-triton/node_modules/cmdln/lib/cmdln.js:917:5)
    at CLI.init (/Users/trentm/joy/node-triton/lib/cli.js:334:30)
    at CLI.cmdlnMain [as main] (/Users/trentm/joy/node-triton/node_modules/cmdln/lib/cmdln.js:677:10)
    at Object.main (/Users/trentm/joy/node-triton/lib/cli.js:683:9)
    at Object.<anonymous> (/Users/trentm/joy/node-triton/bin/triton:12:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by trentm** [comment]
https://cr.joyent.us/#/c/1115/
