### ISSUE TITLE
get cloudapi error body details into Triton CLI error messages

### ISSUE THREAD

**Issue by trentm** [joyent/node-triton#16]
```
...
[2015-09-08T18:24:50.339Z] TRACE: triton/14482 on danger0.local (/Users/trentm/joy/node-triton/node_modules/restify-clients/lib/StringClient.js:166 in done):
    body received:
    {"code":"ValidationFailed","message":"Invalid VM parameters","errors":[{"field":"cpu_cap","code":"Invalid","message":"Not a valid number: number must be >= 0"}]}
joyent-triton create: error (ValidationFailed): ValidationFailedError: Invalid VM parameters
    at parseResponse (/Users/trentm/joy/node-triton/node_modules/restify-clients/lib/JsonClient.js:72:26)
    at IncomingMessage.done (/Users/trentm/joy/node-triton/node_modules/restify-clients/lib/StringClient.js:180:13)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

Specifically, this error was due to a hacked up package (`cpu_cap` set to null), but that "error" response body should get into the error message in general. See possible example from 'sdc-imgapi-cli.git'.

**Comment by trentm** [comment]
This was done in #92
