### ISSUE TITLE
Can't run after commit 3a369e4bb834d0e65a4a030e21c7f9dc9481a7d9

### ISSUE THREAD

**Issue by dillona** [joyent/node-triton#160]
```
➜  node-triton git:(master) node bin/triton
module.js:457
    throw err;
    ^

Error: Cannot find module './constants'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dillona/dev/node-triton/lib/cli.js:28:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

If I go back to the previous commit (2453bc12e819c96b6122874dfdba2e4849d0b227), this does not happen.

I'm running node v6.6.0 on macOS Sierra 10.12.2

**Comment by dillona** [comment]
@cburroughs I believe this was your commit
