### ISSUE TITLE
Integration tests fail to change company name back to original value when it contains spaces

### ISSUE THREAD

**Issue by andrew-wharton** [joyent/node-triton#170]
Just running the integration tests for unrelated changes and got the following error.

```
#  triton account update companyName=<oldvalue>
not ok 54 VError: exec error: command: /bin/sh,-c,/usr/local/Cellar/node/7.0.0/bin/node /Users/andrew/development/node-triton/bin/triton account update companyName=My Company exit status: 1 stdout: stderr: triton account update: error: invalid key=value argument: "Company": Command failed: /bin/sh -c /usr/local/Cellar/node/7.0.0/bin/node /Users/andrew/development/node-triton/bin/triton account update companyName=My Company triton account update: error: invalid key=value argument: "Company"
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { code: 1, jse_cause: { [Error: Command failed: /bin/sh -c /usr/local/Cellar/node/7.0.0/bin/node /Users/andrew/development/node-triton/bin/triton account update companyName=My Company
triton account update: error: invalid key=value argument: "Company"
] killed: false, code: 1, signal: null, cmd: '/bin/sh -c /usr/local/Cellar/node/7.0.0/bin/node /Users/andrew/development/node-triton/bin/triton account update companyName=My Company' }, jse_shortmsg: 'exec error:\n\tcommand: /bin/sh,-c,/usr/local/Cellar/node/7.0.0/bin/node /Users/andrew/development/node-triton/bin/triton account update companyName=My Company\n\texit status: 1\n\tstdout:\n\n\tstderr:\ntriton account update: error: invalid key=value argument: "Company"', jse_summary: 'exec error:\n\tcommand: /bin/sh,-c,/usr/local/Cellar/node/7.0.0/bin/node /Users/andrew/development/node-triton/bin/triton account update companyName=My Company\n\texit status: 1\n\tstdout:\n\n\tstderr:\ntriton account update: error: invalid key=value argument: "Company": Command failed: /bin/sh -c /usr/local/Cellar/node/7.0.0/bin/node /Users/andrew/development/node-triton/bin/triton account update companyName=My Company\ntriton account update: error: invalid key=value argument: "Company"\n', message: 'exec error:\n\tcommand: /bin/sh,-c,/usr/local/Cellar/node/7.0.0/bin/node /Users/andrew/development/node-triton/bin/triton account update companyName=My Company\n\texit status: 1\n\tstdout:\n\n\tstderr:\ntriton account update: error: invalid key=value argument: "Company": Command failed: /bin/sh -c /usr/local/Cellar/node/7.0.0/bin/node /Users/andrew/development/node-triton/bin/triton account update companyName=My Company\ntriton account update: error: invalid key=value argument: "Company"\n' }
    at: Object.ifErr (/Users/andrew/development/node-triton/test/lib/testcommon.js:71:7)
    stack: |-
      VError: exec error:
      	command: /bin/sh,-c,/usr/local/Cellar/node/7.0.0/bin/node /Users/andrew/development/node-triton/bin/triton account update companyName=My Company
      	exit status: 1
      	stdout:

      	stderr:
      triton account update: error: invalid key=value argument: "Company": Command failed: /bin/sh -c /usr/local/Cellar/node/7.0.0/bin/node /Users/andrew/development/node-triton/bin/triton account update companyName=My Company
      triton account update: error: invalid key=value argument: "Company"

          at /Users/andrew/development/node-triton/test/lib/testcommon.js:48:27
          at ChildProcess.exithandler (child_process.js:218:5)
          at emitTwo (events.js:106:13)
          at ChildProcess.emit (events.js:191:7)
          at maybeClose (internal/child_process.js:877:16)
          at Socket.<anonymous> (internal/child_process.js:334:11)
          at emitOne (events.js:96:13)
          at Socket.emit (events.js:188:7)
          at Pipe._handle.close [as _onclose] (net.js:501:12)
  ...
not ok 55 undefined: error body
  ---
    operator: deepEqual
    expected: {}
    actual:   undefined
    at: Object.ifErr (/Users/andrew/development/node-triton/test/lib/testcommon.js:73:11)
  ...
```

**Comment by YangYong3** [comment]
https://cr.joyent.us/#/c/1437/

**Comment by trentm** [comment]
@YangYong3  Thanks. I have a slight alternative here: https://cr.joyent.us/#/c/1499/
