### ISSUE TITLE
`triton ssh ...` can crash if the instance image has no tags

### ISSUE THREAD

**Issue by aarti** [joyent/node-triton#193]
I am using the triton cli successfully and ssh into several servers, however one particular server fails with this exception

```
$triton ssh prod-logservice-1
/Users/aarti/.nvm/versions/node/v7.7.1/lib/node_modules/triton/lib/do_instance/do_ssh.js:79
                if (image.tags.default_user) {
                              ^

TypeError: Cannot read property 'default_user' of undefined
    at /Users/aarti/.nvm/versions/node/v7.7.1/lib/node_modules/triton/lib/do_instance/do_ssh.js:79:31
    at done (/Users/aarti/.nvm/versions/node/v7.7.1/lib/node_modules/triton/lib/tritonapi.js:584:17)
    at next (/Users/aarti/.nvm/versions/node/v7.7.1/lib/node_modules/triton/node_modules/vasync/lib/vasync.js:201:4)
    at Object.cloudApiGetImage [as func] (/Users/aarti/.nvm/versions/node/v7.7.1/lib/node_modules/triton/lib/tritonapi.js:568:21)
    at Immediate.<anonymous> (/Users/aarti/.nvm/versions/node/v7.7.1/lib/node_modules/triton/node_modules/vasync/lib/vasync.js:213:20)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

**Comment by trentm** [comment]
https://cr.joyent.us/#/c/1780/
