### ISSUE TITLE
creating profile with new Docker version scheme fails

### ISSUE THREAD

**Issue by tgross** [joyent/node-triton#196]
`triton profile create` throws an error when it tries to validate the version of the Docker client now that Docker is using a new versioning scheme.

```
Setting up profile "my-new-profile" to use Docker.
/usr/local/lib/node_modules/triton/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 17.04.0-ce-rc2
    at new SemVer (/usr/local/lib/node_modules/triton/node_modules/semver/semver.js:293:11)
    at compare (/usr/local/lib/node_modules/triton/node_modules/semver/semver.js:566:10)
    at Function.gte (/usr/local/lib/node_modules/triton/node_modules/semver/semver.js:615:10)
    at Object.writeSetupJson [as func] (/usr/local/lib/node_modules/triton/lib/do_profile/profilecommon.js:425:31)
    at Immediate._onImmediate (/usr/local/lib/node_modules/triton/node_modules/vasync/lib/vasync.js:213:20)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by misterbisson** [comment]
Is this a duplicate of https://github.com/joyent/node-triton/issues/190?

**Comment by tgross** [comment]
Yeah, this is a dupe https://github.com/joyent/node-triton/issues/190
