### ISSUE TITLE
cli-networks.test.js crash if there are no non-public networks

### ISSUE THREAD

**Issue by trentm** [joyent/node-triton#199]
```
$ TRITON_TEST_CONFIG=test/nightly1.json ./node_modules/.bin/tape test/integration/cli-networks.test.js
TAP version 13
# triton networks
#  triton network list -h
ok 1 null
ok 2 (unnamed assert)
#  triton help networks
ok 3 null
ok 4 (unnamed assert)
#  triton networks
ok 5 null
ok 6 (unnamed assert)
ok 7 (unnamed assert)
#  triton network list
ok 8 null
ok 9 (unnamed assert)
ok 10 (unnamed assert)
#  triton networks public=false
ok 11 null
/Users/trentm/joy/node-triton/lib/common.js:112
        throw new TypeError(errmsg);
        ^

TypeError: invalid boolean value for public: ""
    at Object.boolFromString (/Users/trentm/joy/node-triton/lib/common.js:112:15)
    at /Users/trentm/joy/node-triton/test/integration/cli-networks.test.js:78:39
    at Array.forEach (native)
    at /Users/trentm/joy/node-triton/test/integration/cli-networks.test.js:77:21
    at /Users/trentm/joy/node-triton/test/lib/testcommon.js:59:13
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:854:16)
    at Socket.<anonymous> (internal/child_process.js:330:11)
```

**Comment by trentm** [comment]
https://cr.joyent.us/#/c/1789/

**Comment by trentm** [comment]
The problem was that `stdout.trim().split('\n')` would result in `[""]`.
