### ISSUE TITLE
Assuming an RBAC role in triton CLI v5 throws error

### ISSUE THREAD

**Issue by ajmadsen-hart** [joyent/node-triton#201]
When attempting to assume an RBAC role in triton CLI v5, I receive the error

```
➜ ~ triton -r Devops ls
triton: error (Config): extraneous fields in "default" profile: /Users/me/.triton/profiles.d/default.json: roles
```

If I install triton CLI v4.X, the error goes away. The particular version of the triton CLI that I am using is

```
➜ ~ triton --version
Triton CLI 5.2.0
https://github.com/joyent/node-triton
```

**Comment by trentm** [comment]
Confirmed:

`-r, --role` was added in triton@4.12.0 (issue #120).
It fails in 5.x:

```
$ triton --version; triton -p foo -r Arole images
Triton CLI 5.0.0
https://github.com/joyent/node-triton
triton: error (Config): extraneous fields in "foo" profile: /Users/trentm/.triton/profiles.d/foo.json: roles
```


but works in latest 4.x:

```
$ triton --version; triton -p foo -r Arole images
triton 4.15.0
SHORTID   NAME            VERSION   FLAGS  OS       TYPE          PUBDATE
5917ca96  ubuntu-14.04    20160201  P      linux    lx-dataset    2016-02-01
...
```

**Comment by trentm** [comment]
```
$ triton -v -p foo -r Arole images 2> >(bunyan)
[2017-08-08T22:07:13.820Z] TRACE: triton/99710 on danger0.local (/Users/trentm/joy/node-triton/lib/cli.js:349 in fini): cli fini (subcmd=images, err.code=Config)
    VError: extraneous fields in "foo" profile: /Users/trentm/.triton/profiles.d/foo.json: roles
        at ConfigError._TritonBaseVError (/Users/trentm/joy/node-triton/lib/errors.js:55:12)
        at new ConfigError (/Users/trentm/joy/node-triton/lib/errors.js:139:23)
        at validateProfile (/Users/trentm/joy/node-triton/lib/config.js:252:15)
        at _profileFromPath (/Users/trentm/joy/node-triton/lib/config.js:335:5)
        at Object.loadProfile (/Users/trentm/joy/node-triton/lib/config.js:360:16)
        at CLI.getProfile [as profile] (/Users/trentm/joy/node-triton/lib/cli.js:283:44)
        at CLI.getTritonapi [as tritonapi] (/Users/trentm/joy/node-triton/lib/cli.js:317:30)
        at ImageCLI.do_list (/Users/trentm/joy/node-triton/lib/do_image/do_list.js:70:29)
        at ImageCLI.dispatch (/Users/trentm/joy/node-triton/node_modules/cmdln/lib/cmdln.js:1257:17)
        at CLI.do_images (/Users/trentm/joy/node-triton/lib/do_images.js:16:37)
triton: error (Config): VError: extraneous fields in "foo" profile: /Users/trentm/.triton/profiles.d/foo.json: roles
    at ConfigError._TritonBaseVError (/Users/trentm/joy/node-triton/lib/errors.js:55:12)
    at new ConfigError (/Users/trentm/joy/node-triton/lib/errors.js:139:23)
    at validateProfile (/Users/trentm/joy/node-triton/lib/config.js:252:15)
    at _profileFromPath (/Users/trentm/joy/node-triton/lib/config.js:335:5)
    at Object.loadProfile (/Users/trentm/joy/node-triton/lib/config.js:360:16)
    at CLI.getProfile [as profile] (/Users/trentm/joy/node-triton/lib/cli.js:283:44)
    at CLI.getTritonapi [as tritonapi] (/Users/trentm/joy/node-triton/lib/cli.js:317:30)
    at ImageCLI.do_list (/Users/trentm/joy/node-triton/lib/do_image/do_list.js:70:29)
    at ImageCLI.dispatch (/Users/trentm/joy/node-triton/node_modules/cmdln/lib/cmdln.js:1257:17)
    at CLI.do_images (/Users/trentm/joy/node-triton/lib/do_images.js:16:37)
```

**Comment by trentm** [comment]
CR: https://cr.joyent.us/#/c/2347/

**Comment by trentm** [comment]
This'll be in the next release. Sorry for the delay in fixing this.

**Comment by trentm** [comment]
published now
