### ISSUE TITLE
commit 8438f44 broke parseVolumeSize unit tests

### ISSUE THREAD

**Issue by trentm** [joyent/node-triton#232]
```
$ make test-unit
...
# parsing valid sizes
not ok 149 parsing valid volume size: 42m should not throw
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [Error: size "42m" is not a valid volume size]
    at: parse (/Users/trentm/joy/node-triton/test/unit/parseVolumeSize.test.js:82:15)
    stack: |-
      Error: size "42m" is not a valid volume size
          at throwInvalidSize (/Users/trentm/joy/node-triton/lib/volumes.js:16:11)
          at parseVolumeSize (/Users/trentm/joy/node-triton/lib/volumes.js:36:9)
          at parse (/Users/trentm/joy/node-triton/test/unit/parseVolumeSize.test.js:77:38)
          at Array.forEach (native)
          at Test.<anonymous> (/Users/trentm/joy/node-triton/test/unit/parseVolumeSize.test.js:72:26)
          at Test.bound [as _cb] (/Users/trentm/joy/node-triton/node_modules/tape/lib/test.js:63:32)
          at Test.run (/Users/trentm/joy/node-triton/node_modules/tape/lib/test.js:76:10)
          at Test.bound [as run] (/Users/trentm/joy/node-triton/node_modules/tape/lib/test.js:63:32)
          at Test._end (/Users/trentm/joy/node-triton/node_modules/tape/lib/test.js:142:11)
          at Test.bound [as _end] (/Users/trentm/joy/node-triton/node_modules/tape/lib/test.js:63:32)
  ...
not ok 150 parsed volume size for "42m" should equal to 42 mebibytes
  ---
    operator: equal
    expected: undefined
    actual:   42
    at: parse (/Users/trentm/joy/node-triton/test/unit/parseVolumeSize.test.js:84:15)
  ...
not ok 151 parsing valid volume size: 42M should not throw
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [Error: size "42M" is not a valid volume size]
    at: parse (/Users/trentm/joy/node-triton/test/unit/parseVolumeSize.test.js:82:15)
    stack: |-
      Error: size "42M" is not a valid volume size
          at throwInvalidSize (/Users/trentm/joy/node-triton/lib/volumes.js:16:11)
          at parseVolumeSize (/Users/trentm/joy/node-triton/lib/volumes.js:36:9)
          at parse (/Users/trentm/joy/node-triton/test/unit/parseVolumeSize.test.js:77:38)
          at Array.forEach (native)
          at Test.<anonymous> (/Users/trentm/joy/node-triton/test/unit/parseVolumeSize.test.js:72:26)
          at Test.bound [as _cb] (/Users/trentm/joy/node-triton/node_modules/tape/lib/test.js:63:32)
          at Test.run (/Users/trentm/joy/node-triton/node_modules/tape/lib/test.js:76:10)
          at Test.bound [as run] (/Users/trentm/joy/node-triton/node_modules/tape/lib/test.js:63:32)
          at Test._end (/Users/trentm/joy/node-triton/node_modules/tape/lib/test.js:142:11)
          at Test.bound [as _end] (/Users/trentm/joy/node-triton/node_modules/tape/lib/test.js:63:32)
  ...
not ok 152 parsed volume size for "42M" should equal to 42 mebibytes
  ---
    operator: equal
    expected: undefined
    actual:   42
    at: parse (/Users/trentm/joy/node-triton/test/unit/parseVolumeSize.test.js:84:15)
  ...
not ok 153 parsing valid volume size: 42g should not throw
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [Error: size "42g" is not a valid volume size]
    at: parse (/Users/trentm/joy/node-triton/test/unit/parseVolumeSize.test.js:82:15)
    stack: |-
      Error: size "42g" is not a valid volume size
          at throwInvalidSize (/Users/trentm/joy/node-triton/lib/volumes.js:16:11)
          at parseVolumeSize (/Users/trentm/joy/node-triton/lib/volumes.js:36:9)
          at parse (/Users/trentm/joy/node-triton/test/unit/parseVolumeSize.test.js:77:38)
          at Array.forEach (native)
          at Test.<anonymous> (/Users/trentm/joy/node-triton/test/unit/parseVolumeSize.test.js:72:26)
          at Test.bound [as _cb] (/Users/trentm/joy/node-triton/node_modules/tape/lib/test.js:63:32)
          at Test.run (/Users/trentm/joy/node-triton/node_modules/tape/lib/test.js:76:10)
          at Test.bound [as run] (/Users/trentm/joy/node-triton/node_modules/tape/lib/test.js:63:32)
          at Test._end (/Users/trentm/joy/node-triton/node_modules/tape/lib/test.js:142:11)
          at Test.bound [as _end] (/Users/trentm/joy/node-triton/node_modules/tape/lib/test.js:63:32)
  ...
not ok 154 parsed volume size for "42g" should equal to 43008 mebibytes
  ---
    operator: equal
    expected: undefined
    actual:   43008
    at: parse (/Users/trentm/joy/node-triton/test/unit/parseVolumeSize.test.js:84:15)
  ...
ok 155 parsing valid volume size: 42G should not throw
ok 156 parsed volume size for "42G" should equal to 43008 mebibytes
```

The unit tests weren't updated with commit 8438f44

**Comment by trentm** [comment]
That commit dropped support for 'm', 'M', and 'g' volume size unit suffixes.

**Comment by trentm** [comment]
CR https://cr.joyent.us/#/c/2657/

**Comment by trentm** [comment]
Fixed: ^
