### ISSUE TITLE
Error when creating or deleting profiles when using node v10

### ISSUE THREAD

**Issue by SamWhited** [joyent/node-triton#249]
Part way through creating a profile this happened, now I can not delete it either:

```
$ triton profile delete us-sw-1
Delete profile "us-sw-1"? [y/n] yevents.js:167
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:75:25)
    at writeGeneric (internal/stream_base_commons.js:70:3)
    at ReadStream.Socket._writeGeneric (net.js:760:5)
    at ReadStream.Socket._write (net.js:772:8)
    at doWrite (_stream_writable.js:413:12)
    at writeOrBuffer (_stream_writable.js:397:5)
    at ReadStream.Writable.write (_stream_writable.js:295:11)
    at postInput (/usr/lib/node_modules/triton/lib/common.js:623:15)
    at ReadStream.onData (/usr/lib/node_modules/triton/lib/common.js:647:13)
    at ReadStream.emit (events.js:182:13)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:433:12)
    at onwrite (_stream_writable.js:469:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at ReadStream.Socket._destroy (net.js:605:3)
    at ReadStream.destroy (internal/streams/destroy.js:36:8)
    at afterWriteDispatched (internal/stream_base_commons.js:75:17)
    at writeGeneric (internal/stream_base_commons.js:70:3)
    [... lines matching original stack trace ...]
    at doWrite (_stream_writable.js:413:12)
```

I have installed the tool using the [AUR package](https://aur.archlinux.org/packages/nodejs-triton/).

**Comment by glasspelican** [comment]
I get the same error when attempting to delete snapshots from an instance, same stack trace

```
➜  ~ triton inst snapshot rm <redacted> 20180423T183352Z 20180430T194140Z 20180504T184418Z 20180508T174235Z
Delete 4 snapshots (20180423T183352Z, 20180430T194140Z, 20180504T184418Z, 20180508T174235Z)? [y/n] yevents.js:167
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:75:25)
    at writeGeneric (internal/stream_base_commons.js:70:3)
    at ReadStream.Socket._writeGeneric (net.js:760:5)
    at ReadStream.Socket._write (net.js:772:8)
    at doWrite (_stream_writable.js:413:12)
    at writeOrBuffer (_stream_writable.js:397:5)
    at ReadStream.Writable.write (_stream_writable.js:295:11)
    at postInput (/usr/local/lib/node_modules/triton/lib/common.js:623:15)
    at ReadStream.onData (/usr/local/lib/node_modules/triton/lib/common.js:647:13)
    at ReadStream.emit (events.js:182:13)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:428:12)
    at onwrite (_stream_writable.js:459:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at ReadStream.Socket._destroy (net.js:605:3)
    at ReadStream.destroy (internal/streams/destroy.js:32:8)
    at afterWriteDispatched (internal/stream_base_commons.js:75:17)
    at writeGeneric (internal/stream_base_commons.js:70:3)
    [... lines matching original stack trace ...]
    at doWrite (_stream_writable.js:413:12)
```

Macos 10.13.4
node v10.1.0
npm 5.6.0
Triton CLI 6.0.0

Triton cli was installed via npm

**Comment by sparecycles** [comment]
Works for me with `node v8.11.2` (current LTS), did not work with `v10.2.0`.

Looks like a regression.

**Comment by mariuspana** [comment]
I uninstalled the nodejs and npm versions previously installed and downloaded the LTS version (8.11.3) and now things work.

node v8.11.3 
npm 5.6.0

**Comment by Teutone** [comment]
Confirming regression with node v10.6.0. Doesn't generally break triton profile setup though. Seems related to docker-setup only.

**Comment by SamWhited** [comment]
I got this again today while trying to fetch my certificates:

```
$ triton profile docker-setup
WARNING: Docker uses authentication via client TLS certificates that do not
support encrypted (passphrase protected) keys or SSH agents. If you continue,
this profile setup will attempt to write a copy of your SSH private key
formatted as an unencrypted TLS certificate in "~/.triton/docker" for use by
the Docker client.

Continue? [y/n] yevents.js:167
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:75:25)
    at writeGeneric (internal/stream_base_commons.js:70:3)
    at ReadStream.Socket._writeGeneric (net.js:760:5)
    at ReadStream.Socket._write (net.js:772:8)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at ReadStream.Writable.write (_stream_writable.js:294:11)
    at postInput (/home/sam/node_modules/triton/lib/common.js:623:15)
    at ReadStream.onData (/home/sam/node_modules/triton/lib/common.js:647:13)
    at ReadStream.emit (events.js:182:13)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:425:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at ReadStream.Socket._destroy (net.js:605:3)
    at ReadStream.destroy (internal/streams/destroy.js:32:8)
    at afterWriteDispatched (internal/stream_base_commons.js:75:17)
    at writeGeneric (internal/stream_base_commons.js:70:3)
    [... lines matching original stack trace ...]
    at doWrite (_stream_writable.js:410:12)
```

This is extremely critical for me now, and I would appreciate any advice on how I can fix this or if there's some other way for me to get a copy of my certs.

**Comment by twhiteman** [comment]
I can reproduce this on Node v10.7.0.

It appears to be related to stdin input reading.

Removing this line (I don't understand why it's trying to write to stdin!?):
https://github.com/joyent/node-triton/blob/dc5dc12052b152759295c33d967d0f3d5de126de/lib/common.js#L623
stops this exception from occurring in node v10.7.0.

@trentm Do you know the reasoning for the stdin.write?

**Comment by trentm** [comment]
@twhiteman No, I don't know why that `stdin.write()` is there. I think my code here dates back to `HEAD-1795: first stab at 'sdcadm update SERVICE'` to sdcadm.git over 4 years ago.  Would you be able to test against an old node (e.g. 0.10) to see if that promptYesNo still works?

Note to self to get this fix out to other places using my promptYesNo: sdcadm, jirash, engadm, joyent-repos, imgadm, trentops.

**Comment by SamWhited** [comment]
At a guess: this appears to be ensuring that a read always ends with a newline; this is normally something you'd have anyways except that it's reading in raw mode so if you're piping data in or if the newline is consumed by whatever checks for it you might not. I didn't look to see if anything else was relying on all reads being newline terminated though. I've had to work around similar problems when not using readline(3), but I'm also not at all familiar with JavaScript and generally try to avoid having things that require runtimes like this, so of course I may be misunderstanding entirely.

**Comment by trentm** [comment]
triton@6.1.2 published with todd's fix.
