### ISSUE TITLE
Error when running docker-setup

### ISSUE THREAD

**Issue by SamWhited** [joyent/node-triton#253]
Similar to #249, just about any time I need to use the triton CLI tool I get panics. The latest one is when trying to get a copy of my docker certificates (if there is some other way to get these, I would appreciate any advice, I couldn't find anything searching the web).

I am not sure if this is the same error or not, so I filed a new issue. It is more critical for me now though.

```
$ triton profile docker-setup
WARNING: Docker uses authentication via client TLS certificates that do not
support encrypted (passphrase protected) keys or SSH agents. If you continue,
this profile setup will attempt to write a copy of your SSH private key
formatted as an unencrypted TLS certificate in "~/.triton/docker" for use by
the Docker client.

Continue? [y/n] yevents.js:167
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:75:25)
    at writeGeneric (internal/stream_base_commons.js:70:3)
    at ReadStream.Socket._writeGeneric (net.js:760:5)
    at ReadStream.Socket._write (net.js:772:8)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at ReadStream.Writable.write (_stream_writable.js:294:11)
    at postInput (/home/sam/node_modules/triton/lib/common.js:623:15)
    at ReadStream.onData (/home/sam/node_modules/triton/lib/common.js:647:13)
    at ReadStream.emit (events.js:182:13)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:425:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at ReadStream.Socket._destroy (net.js:605:3)
    at ReadStream.destroy (internal/streams/destroy.js:32:8)
    at afterWriteDispatched (internal/stream_base_commons.js:75:17)
    at writeGeneric (internal/stream_base_commons.js:70:3)
    [... lines matching original stack trace ...]
    at doWrite (_stream_writable.js:410:12)
```

Other possibly useful info:

```
$ node --version
v10.6.0
 $ npm --version
6.2.0
$ uname -a
Linux … 4.17.5-1-ARCH #1 SMP PREEMPT Sun Jul 8 17:27:31 UTC 2018 x86_64 GNU/Linux
```

**Comment by SamWhited** [comment]
Sorry, this is a duplicate. I'd missed a comment from the other issue that said this was related to docker-setup.
