### ISSUE TITLE
fs.unlink() requires a callback

### ISSUE THREAD

**Issue by papertigers** [joyent/node-triton#281]
barfield on IRC reported this issue while trying to setup a docker profile:

```
fs.js:154
    throw new ERR_INVALID_CALLBACK(cb);
    ^
 
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (fs.js:154:11)
    at Object.unlink (fs.js:1035:14)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/triton/lib/do_profile/profilecommon.js:72:12)
    at ClientRequest.emit (events.js:209:13)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:209:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

It looks like in `downloadUrl()` in the request error handler, we don't currently provide `fs.unlink()` a callback which is hiding the users original issue.

**Comment by bhechinger** [comment]
With version Triton CLI 7.5.1 I'm having this exact same issue.

```
fs.js:151
    throw new ERR_INVALID_CALLBACK(cb);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (fs.js:151:11)
    at Object.unlink (fs.js:1057:14)
    at ClientRequest.<anonymous> (/usr/lib/node_modules/triton/lib/do_profile/profilecommon.js:72:12)
    at ClientRequest.emit (events.js:321:20)
    at TLSSocket.socketErrorListener (_http_client.js:424:9)
    at TLSSocket.emit (events.js:321:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ERR_INVALID_CALLBACK'
}
```

**Comment by trentm** [comment]
Would anyone like to test this diff:

```diff
diff --git a/lib/do_profile/profilecommon.js b/lib/do_profile/profilecommon.js
index 5f6cac5..c8b67ce 100644
--- a/lib/do_profile/profilecommon.js
+++ b/lib/do_profile/profilecommon.js
@@ -26,6 +26,7 @@ var sshpk = require('sshpk');
 var mod_url = require('url');
 var crypto = require('crypto');
 var vasync = require('vasync');
+var VError = require('verror');
 var which = require('which');
 var wordwrap = require('wordwrap')(78);
 
@@ -69,8 +70,13 @@ function downloadUrl(opts, cb) {
     });
 
     req.on('error', function (err) {
-        fs.unlink(opts.dest);
-        cb(err);
+        fs.unlink(opts.dest, function onUnlink(unlinkErr) {
+            if (unlinkErr) {
+                cb(VError.errorFromList[err, unlinkErr]);
+            } else {
+                cb(err);
+            }
+        });
     });
 }
```

?

**Comment by bhechinger** [comment]
```# Docker setup

This section will setup authentication to Triton DataCenter's Docker endpoint
using your account and key information specified above. This is only required
if you intend to use `docker` with this profile.

WARNING: Docker uses authentication via client TLS certificates that do not
support encrypted (passphrase protected) keys or SSH agents.

If you continue, this profile setup will create a fresh private key to be
written unencrypted to disk in "~/.triton/docker" for use by the Docker
client. This key will be useable only for Docker.

If you do not specifically want to use Docker, you can answer "no" here.

Continue? [y/n] y

Setting up profile "testing" to use Docker.
triton profile create: error (DEPTH_ZERO_SELF_SIGNED_CERT): self signed certificate
```

**Comment by trentm** [comment]
@bhechinger Thanks! So *better*, then.

**Comment by bhechinger** [comment]
Considering it actually tells me what's wrong now, yes. Much better. :)

**Comment by trentm** [comment]
Oops, I assume you fixed the syntax error in my untested patch.

**Comment by bhechinger** [comment]
I did not. It just worked as is.

**Comment by trentm** [comment]
> I did not. It just worked as is.

Ah, not syntax error, but rather invalid calling of the `errorFromList` function in a code path you didn't hit.

**Comment by trentm** [comment]
triton@7.7.1 is published with this
