### ISSUE TITLE
Issues with npm 3

### ISSUE THREAD

**Issue by chorrell** [joyent/node-triton#56]
I have a recent version of npm 3:

```
[christopher@MacBook ~]$ npm version
{ npm: '3.3.10',
  ares: '1.9.0-DEV',
  http_parser: '1.0',
  modules: '11',
  node: '0.10.40',
  openssl: '1.0.1p',
  uv: '0.10.36',
  v8: '3.14.5.9',
  zlib: '1.2.8' }
```

Installing triton (`sudo npm install -g triton`) throws a warning about sshpk:

```
npm WARN EPEERINVALID http-signature@1.0.2 requires a peer of sshpk@^1.4.6 but none was installed.
```

And commands like `triton ls` fail:

```
[christopher@MacBook ~]$ triton ls

assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: key
    at Object.module.exports.(anonymous function) [as ok] (/usr/local/lib/node_modules/triton/node_modules/smartdc-auth/node_modules/sshpk/node_modules/assert-plus/assert.js:242:35)
    at Fingerprint.matches (/usr/local/lib/node_modules/triton/node_modules/smartdc-auth/node_modules/sshpk/lib/fingerprint.js:51:9)
    at /usr/local/lib/node_modules/triton/node_modules/smartdc-auth/lib/index.js:366:24
    at /usr/local/lib/node_modules/triton/node_modules/sshpk-agent/lib/client.js:80:3
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/sshpk-agent/lib/client.js:365:3)
    at EventEmitter.emit (events.js:95:17)
    at AgentDecodeStream.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/sshpk-agent/lib/client.js:473:18)
    at AgentDecodeStream.emit (events.js:92:17)
    at emitReadable_ (/usr/local/lib/node_modules/triton/node_modules/readable-stream/lib/_stream_readable.js:464:10)
    at emitReadable (/usr/local/lib/node_modules/triton/node_modules/readable-stream/lib/_stream_readable.js:458:7)

```

**Comment by trentm** [comment]
For me (using node 5.0.0 and npm 3.3.6):

```
[15:06:52 trentm@danger0:~/tmp/play]
$ npm install triton

> dtrace-provider@0.6.0 install /Users/trentm/tmp/play/node_modules/dtrace-provider
> node scripts/install.js

play@1.0.0 /Users/trentm/tmp/play
└── triton@3.4.1  extraneous

npm WARN EPACKAGEJSON play@1.0.0 No description
npm WARN EPACKAGEJSON play@1.0.0 No repository field.
[15:07:10 trentm@danger0:~/tmp/play]
$ echo $?
0
```

Seems to work for me:

```
$ ./node_modules/.bin/triton insts
SHORTID   NAME                IMG                                   STATE    PRIMARYIP        AGO
787cd9f7  nginx               b107dc88-1e84-c82a-69df-f2639b16dc5c  stopped  165.225.169.64   15w
4e0a3913  bf2a012             minimal-64-lts@14.4.2                 running  165.225.171.204  9w
a02e77b0  ae40f7e8            base@14.3.0                           running  165.225.168.31   8w
4f1823c4  a0c5a497            base@14.3.0                           running  165.225.168.32   8w
4ba0d73a  influx4             98d0ab43-413c-600f-c720-c3f863a27809  stopped  165.225.170.153  3w
5a318b2f  grafana4            fc6c27e1-52f8-3e0d-d9b2-d2ee34d634cc  stopped  165.225.168.83   3w
21646686  test0               minimal-32@15.3.0                     running  165.225.168.129  3w
0311dadb  nginx-terraform-01  a23c9a08-089d-134b-c85e-f656e514549e  running  165.225.168.228  2w
62609fb1  test-machine        ubuntu-15.04@20151105                 running  165.225.168.229  2w
```

etc.

@chorrell Can you still repro? Perhaps http-signature/sshpk have sorted this out separately?

**Comment by chorrell** [comment]
I'll take a look at this later this week.

**Comment by chorrell** [comment]
I just installed Node.js 5.3.0 with npm 3.3.12 and it it looks like it's all good now:

**Comment by chorrell** [comment]
(I did a clean installed, deleted /usr/local/lib/node_modules/)
