### ISSUE TITLE
triton create error in v4.3.0

### ISSUE THREAD

**Issue by askfongjojo** [joyent/node-triton#77]
triton inst create --name=sanitycheck --network=Joyent-SDC-Public base64 t4-standard-512M

module.js:340
    throw err;
    ^
Error: Cannot find module '../metadataandtags'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/lib/do_image/do_create.js:24:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by trentm** [comment]
thanks!

triton@4.3.1 pushed with fix (forgot to add that file)
