### ISSUE TITLE
Dependency problem installing as project dependency

### ISSUE THREAD

**Issue by cehoffman** [joyent/node-triton#90]
I have this tool as a dependency in my project because I use the programatic interface exposed to query the cloudapi for information. However I have a consistent problem on installation that I have to manually fix to get **sshpk** and **sshpk-agent** to play nice across **http-signature**, **smartdc-auth**, and this tool.

The problem manifests itself as this error.

~~~
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: key
    at Object.module.exports.(anonymous function) [as ok] (/Users/cehoffman/Projects/work/verify-ui/node_modules/sshpk/node_modules/assert-plus/assert.js:242:35)
    at Fingerprint.matches (/Users/cehoffman/Projects/work/verify-ui/node_modules/sshpk/lib/fingerprint.js:51:9)
    at /Users/cehoffman/Projects/work/verify-ui/node_modules/smartdc-auth/lib/index.js:366:24
    at /Users/cehoffman/Projects/work/verify-ui/node_modules/sshpk-agent/lib/client.js:80:3
    at EventEmitter.<anonymous> (/Users/cehoffman/Projects/work/verify-ui/node_modules/sshpk-agent/lib/client.js:365:3)
    at emitOne (events.js:90:13)
    at EventEmitter.emit (events.js:182:7)
    at AgentDecodeStream.<anonymous> (/Users/cehoffman/Projects/work/verify-ui/node_modules/sshpk-agent/lib/client.js:473:18)
    at emitNone (events.js:80:13)
    at AgentDecodeStream.emit (events.js:179:7)
    at emitReadable_ (/Users/cehoffman/Projects/work/verify-ui/node_modules/sshpk-agent/node_modules/readable-stream/lib/_stream_readable.js:466:10)
    at emitReadable (/Users/cehoffman/Projects/work/verify-ui/node_modules/sshpk-agent/node_modules/readable-stream/lib/_stream_readable.js:460:7)
    at readableAddChunk (/Users/cehoffman/Projects/work/verify-ui/node_modules/sshpk-agent/node_modules/readable-stream/lib/_stream_readable.js:212:11)
    at AgentDecodeStream.Readable.push (/Users/cehoffman/Projects/work/verify-ui/node_modules/sshpk-agent/node_modules/readable-stream/lib/_stream_readable.js:165:10)
    at AgentDecodeStream.Transform.push (/Users/cehoffman/Projects/work/verify-ui/node_modules/sshpk-agent/node_modules/readable-stream/lib/_stream_transform.js:133:32)
    at AgentDecodeStream._transform (/Users/cehoffman/Projects/work/verify-ui/node_modules/sshpk-agent/lib/protocol-streams.js:216:9)
    at AgentDecodeStream.Transform._read (/Users/cehoffman/Projects/work/verify-ui/node_modules/sshpk-agent/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at AgentDecodeStream.Transform._write (/Users/cehoffman/Projects/work/verify-ui/node_modules/sshpk-agent/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/cehoffman/Projects/work/verify-ui/node_modules/sshpk-agent/node_modules/readable-stream/lib/_stream_writable.js:335:12)
    at writeOrBuffer (/Users/cehoffman/Projects/work/verify-ui/node_modules/sshpk-agent/node_modules/readable-stream/lib/_stream_writable.js:321:5)
    at AgentDecodeStream.Writable.write (/Users/cehoffman/Projects/work/verify-ui/node_modules/sshpk-agent/node_modules/readable-stream/lib/_stream_writable.js:248:11)
    at Socket.ondata (_stream_readable.js:529:20)
~~~

I use `npm shrinkwrap` to show a diff of my modules between an initial install and a working modification.

~~~diff
diff --git a/npm-shrinkwrap.json b/npm-shrinkwrap.json
index 0fcbc73..e1a5d93 100644
--- a/npm-shrinkwrap.json
+++ b/npm-shrinkwrap.json
@@ -5445,18 +5445,6 @@
           "from": "once@1.3.0",
           "resolved": "https://registry.npmjs.org/once/-/once-1.3.0.tgz"
         },
-        "sshpk": {
-          "version": "1.6.2",
-          "from": "sshpk@1.6.2",
-          "resolved": "https://registry.npmjs.org/sshpk/-/sshpk-1.6.2.tgz",
-          "dependencies": {
-            "assert-plus": {
-              "version": "0.1.5",
-              "from": "assert-plus@>=0.1.5 <0.2.0",
-              "resolved": "https://registry.npmjs.org/assert-plus/-/assert-plus-0.1.5.tgz"
-            }
-          }
-        },
         "vasync": {
           "version": "1.4.3",
           "from": "vasync@1.4.3",
@@ -5613,7 +5601,7 @@
     },
     "sshpk": {
       "version": "1.6.2",
-      "from": "sshpk@1.6.2",
+      "from": "sshpk@>=1.6.0 <1.7.0 >=1.6.2",
       "resolved": "https://registry.npmjs.org/sshpk/-/sshpk-1.6.2.tgz",
       "dependencies": {
         "assert-plus": {
@@ -5637,11 +5625,6 @@
           "version": "2.0.5",
           "from": "readable-stream@>=2.0.0 <3.0.0",
           "resolved": "https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.5.tgz"
-        },
-        "sshpk": {
-          "version": "1.6.2",
-          "from": "sshpk@>=1.4.4 <1.7.0",
-          "resolved": "https://registry.npmjs.org/sshpk/-/sshpk-1.6.2.tgz"
         }
       }
     },
@@ -5997,18 +5980,6 @@
           "from": "rimraf@2.4.4",
           "resolved": "https://registry.npmjs.org/rimraf/-/rimraf-2.4.4.tgz"
         },
-        "sshpk": {
-          "version": "1.6.2",
-          "from": "sshpk@>=1.6.0 <1.7.0 >=1.6.2",
-          "resolved": "https://registry.npmjs.org/sshpk/-/sshpk-1.6.2.tgz",
-          "dependencies": {
-            "assert-plus": {
-              "version": "0.1.5",
-              "from": "assert-plus@>=0.1.5 <0.2.0",
-              "resolved": "https://registry.npmjs.org/assert-plus/-/assert-plus-0.1.5.tgz"
-            }
-          }
-        },
         "verror": {
           "version": "1.6.0",
           "from": "verror@1.6.0",
~~~

This is moving sshpk from a dependency resolved on `triton`, `smartdc-auth`, and `sshpk-agent` to a single top level resolution. I guess this could be solved by making more use of peer dependencies.

**Comment by trentm** [comment]
Hopefully a fix for this in version 4.4.4 (published just now).

**Comment by trentm** [comment]
see commit c785a430c6f9796247a1d5e4299a2312142a0806

**Comment by cehoffman** [comment]
Can confirm, that fixed the problem for me.
